substitutions:
  device_name: basement-stairs-mmwave-c3
  device_name_pretty: "basement stairs mmwave c3"
  
esphome:
  name: ${device_name}
  friendly_name: ${device_name_pretty}
  includes:
    - leapmmw_sensor.h
    
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG  #You Can Use "INFO" Level
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "m/VImzYhHfGuPU0NyGGiP/6tJlcv8JPy9pDXG2UtqiE="

ota:
  password: "ebfa17f36e2d90de09facad6650e8944"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Basement-Stairs-Mmwave-C3"
    password: "uoD8kJDKcaXq"

captive_portal:
    