esphome:
  name: "basement-stairs"
  friendly_name: basement stairs upper motion

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "J1Pl6cIH8ormuwRNFrCU49bVDtFAOE+4r4oboq8gJnM="

ota:
  password: "d735909e801bb482b0989c3befb43865"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Basement-Stairs-Upper-Motion"
    password: "sFbohjRvYyMn"

captive_portal:
    
binary_sensor:
  - platform: gpio
    pin: GPIO7
    name: "PIR Sensor"
    device_class: motion
    on_press: 
      then:
        light.turn_on: 
          id: status_light
          red: 10%
          green: 0%
          blue: 0%
    on_release:
      then:
        light.turn_off: status_light
        

light:
  - platform: neopixelbus
    id: status_light
    type: GRB
    variant: WS2811
    pin: GPIO8
    num_leds: 1
    name: "Status Light"
    internal: True

  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO9
    num_leds: 60
    name: "Stairs Right"