esphome:
  name: basement-stairs-upper-motion-sensor
  friendly_name: basement stairs upper motion sensor

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "JAlRbqj1ibnN5gMo3eXS/7jqSaaTbSy09APYSWNUb0c="

ota:
  password: "90e404650dd4953147f82e5e257be7b5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Basement-Stairs-Upper-Motion-Sensor"
    password: "higGVbGCXDPT"

captive_portal:
    