esphome:
  name: basement-stairs-led-controller
  friendly_name: basement stairs led controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1zN1Evl3kkRYTLWmSw+iLL6Gpufn/QJru2X17YroAns="

ota:
  password: "d980c05ac4810f46717c0d8ea10b3b2b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Basement-Stairs-Led-Controller"
    password: "tJdG3X0m0TcY"

captive_portal:
    