esphome:
  name: corner-sump-water-level-sensor
  friendly_name: corner-sump-water-level-sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "92TRSyzjZq5bbw8/wipmn7zWZWC2XPmxNEbJZv6+M30="

ota:
  password: "18cb2f0dd54a6bd7e56c3e5e79efe314"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Corner-Sump-Water-Level-Sensor"
    password: "UGeBCJnN3PX2"

captive_portal:

# https://learn.sparkfun.com/tutorials/esp32-thing-plus-hookup-guide/all
# https://esphome.io/components/i2c.html#
# https://learn.sparkfun.com/tutorials/qwiic-ultrasonic-distance-sensor-hc-sr04-hookup-guide/all
i2c:
  sda: GPIO01
  scl: GPIO02
  scan: true
  id: bus_a