esphome:
  name: garage-master
  friendly_name: garage-master
  comment: esp32dev
  
esp32:
  board: esp32dev
  framework:
    type: arduino

# Disable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "RoWkhYIHXIB92Q4zNPcweZvZgWSChT1A1oRmD2hRolk="

ota:
  password: "c279b490f4994e36755058ed0e40460b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Master Fallback Hotspot"
    password: "a5ZRCKrJLKVt"

captive_portal:

uart:
  rx_pin: GPIO1
  tx_pin: GPIO3
  baud_rate: 115200
  data_bits: 8
  stop_bits: 1
  parity: NONE
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);


external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components #Thanks for @ssieb components.
    components: [ serial ]

    
# text_sensor:
#   - platform: serial
#     name: Slave text

text:
  - platform: template
    mode: text
    name: Send to slave
    id: send_to_slave
    set_action:
      then:
        - uart.write: !lambda |-
            std::string sendme = x + "\n";
            return std::vector<uint8_t>(sendme.begin(), sendme.end());
