esphome:
  name: garage-wifi-slave
  friendly_name: garage-wifi-slave

esp32:
  board: esp32dev
  framework:
    type: arduino

# Disable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "M64t2wRHjGVpPBAu6AxxRKY3WyZLdB3yK7jQOJyE5AU="

ota:
  password: "abf5c4123fd2db9bf4c5aef1237f4243"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Slave Fallback Hotspot"
    password: "f2XLmIgz8PaN"

captive_portal:
    

uart:
  rx_pin: GPIO22
  tx_pin: GPIO23
  baud_rate: 9600
  data_bits: 8
  stop_bits: 1
  parity: NONE
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
    
# text_sensor:
#   - platform: serial
#     id: master_text
#     name: Master text

text:
  - platform: template
    mode: text
    name: Send to master
    id: send_to_master
    set_action:
      then:
        - uart.write: !lambda |-
            std::string sendme = x + "\n";
            return std::vector<uint8_t>(sendme.begin(), sendme.end());