esphome:
  name: garage-ha-master
  friendly_name: garage-ha-master

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "voq2rWJn8dFl/rtHRAqAnIipjcwWqdh/WAAn6BEle3Y="

ota:
  password: "84faa1ee621712bd8c06f8382b7c1fda"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Ha-Master"
    password: "0OyBvaAOSOcL"

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components #Thanks for @ssieb components.
    components: [ serial ]

# Enable logging
logger:
  baud_rate: 0

uart:
  rx_pin: GPIO22
  tx_pin: GPIO23
  baud_rate: 9600
  data_bits: 8
  stop_bits: 2
  parity: NONE
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
    
text_sensor:
  - platform: serial
    name: Received slave text
    id: slave_text

text:
  - platform: template
    mode: text
    name: Send to slave
    id: send_to_slave
    set_action:
      then:
        - uart.write: !lambda |-
            std::string sendme = x + "\n";
            return std::vector<uint8_t>(sendme.begin(), sendme.end());