# This file is included as a package in all mmwave presence sensors
# Requires area variable to be set to the name of the room the sensor is in.
#
# Parameters passed in:
#   - ${area} - name of the area this file is included in
#
esphome:
  comment: "Beacon"

# System time config - required for precise timestamps, used in integration:
time:
  - platform: homeassistant
    id: homeassistant_time

bluetooth_proxy:

esp32_ble_tracker:

