esphome:
  comment: Sen0395

# Disable uart logging
logger:
  baud_rate: 0
  level: DEBUG

uart:
  id: SEN0395_UART_BUS
  rx_pin: ${uart_rx_pin}
  tx_pin: ${uart_tx_pin}
  baud_rate: 115200
  data_bits: 8
  stop_bits: 1
  parity: NONE

dfrobot_sen0395:
  - uart_id: SEN0395_UART_BUS

binary_sensor:
  - platform: gpio
    name: "${device_name_pretty}"
    id: mmwave_presence_detection
    device_class: motion
    pin:
      number: ${presence_pin}
      mode: INPUT_PULLDOWN
